#ifndef GFX_MINIMAP_LEVELS_H
#define GFX_MINIMAP_LEVELS_H

#include "minimap_types.h"

extern const struct MiniMapInfo *level_info[];

/* these are generated at build time */
#include "src/minimap/textures/bbh_t3x.h"
#include "src/minimap/textures/bitdw_t3x.h"
#include "src/minimap/textures/bitfs_t3x.h"
#include "src/minimap/textures/bits_t3x.h"
#include "src/minimap/textures/bob_t3x.h"
#include "src/minimap/textures/bowser_1_t3x.h"
#include "src/minimap/textures/bowser_2_t3x.h"
#include "src/minimap/textures/bowser_3_t3x.h"
#include "src/minimap/textures/castle_1_t3x.h"
#include "src/minimap/textures/castle_2_t3x.h"
#include "src/minimap/textures/castle_3_t3x.h"
#include "src/minimap/textures/castle_courtyard_t3x.h"
#include "src/minimap/textures/castle_grounds_t3x.h"
#include "src/minimap/textures/castle_grounds_drained_t3x.h"
#include "src/minimap/textures/ccm_1_t3x.h"
#include "src/minimap/textures/ccm_2_t3x.h"
#include "src/minimap/textures/cotmc_t3x.h"
#include "src/minimap/textures/ddd_1_t3x.h"
#include "src/minimap/textures/ddd_2_t3x.h"
#include "src/minimap/textures/hmc_t3x.h"
#include "src/minimap/textures/jrb_1_t3x.h"
#include "src/minimap/textures/jrb_2_t3x.h"
#include "src/minimap/textures/lll_1_t3x.h"
#include "src/minimap/textures/lll_2_t3x.h"
#include "src/minimap/textures/pss_t3x.h"
#include "src/minimap/textures/rr_t3x.h"
#include "src/minimap/textures/sa_t3x.h"
#include "src/minimap/textures/sl_1_t3x.h"
#include "src/minimap/textures/sl_2_t3x.h"
#include "src/minimap/textures/ssl_1_t3x.h"
#include "src/minimap/textures/ssl_2_t3x.h"
#include "src/minimap/textures/ssl_3_t3x.h"
#include "src/minimap/textures/thi_1_t3x.h"
#include "src/minimap/textures/thi_2_t3x.h"
#include "src/minimap/textures/thi_3_t3x.h"
#include "src/minimap/textures/totwc_t3x.h"
#include "src/minimap/textures/ttc_t3x.h"
#include "src/minimap/textures/ttm_1_t3x.h"
#include "src/minimap/textures/ttm_2_t3x.h"
#include "src/minimap/textures/ttm_3_t3x.h"
#include "src/minimap/textures/ttm_4_t3x.h"
#include "src/minimap/textures/unknown_t3x.h"
#include "src/minimap/textures/vcutm_t3x.h"
#include "src/minimap/textures/wdw_1_t3x.h"
#include "src/minimap/textures/wdw_2_t3x.h"
#include "src/minimap/textures/wmotr_t3x.h"
#include "src/minimap/textures/wf_t3x.h"

#endif
